### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by MarcAnt01** [robmikh/SimpleRecorder#21]
Are you considering the possibility to record audio along with the video? Is that allowed by the APIs you use

**Comment by robmikh** [comment]
This sample is primarily about using the Windows.Graphics.Capture and Windows.Media.Transcoding APIs. Windows.Graphics.Capture only has the ability to capture graphical content. Windows.Media.Transcoding has the ability to add-in an audio stream, I believe, but you need to get the audio from somewhere else first.

There are two ways you can go about this:
- Some systems have a synthetic loopback audio device that can be used as a micrphone in the [AudioGraph ](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Audio.AudioGraph?view=winrt-19041) API. This is less consistent, mainly because not all systems are guaranteed to have this synthetic device. For example, my system has a device called "What U Hear" and it comes from my Sound Blaster audio device integrated into my motherboard.
- Use WASAPI to record loopback audio. It's a C++ API, but you may be able to find some C# bindings somewhere. This is probably the more robust option.

This project may in the future explore audio recording, but it isn't an immediate goal that I have.

**Comment by MarcAnt01** [comment]
Thanks a lot for the detailed explanation
