### ISSUE TITLE
Latest version started recording with black corner

### ISSUE THREAD

**Issue by WORMSS** [robmikh/SimpleRecorder#35]
There seems to be a black pattern that has started to appear when I reinstalled this app.

![image](https://user-images.githubusercontent.com/1384537/125352508-45593200-e359-11eb-9bac-64eb0d790564.png)

The pattern is different 
![image](https://user-images.githubusercontent.com/1384537/125352657-746fa380-e359-11eb-951e-5c1c5d280108.png)

Depending on the size of the window.

I am unsure what has changed recently to have caused this? If it was a windows update (Which I am forced to do by my works admin policies)

**Comment by robmikh** [comment]
Hmm that looks like it would be an issue coming from your video card driver. What build of Windows are you running and what do you have for CPU/GPU? Have you already tried getting the latest GPU driver for your setup?

**Comment by WORMSS** [comment]
`Intel Zeon E5-1620 v3`
`Windows 10 Pro 21H1`
The graphics card I do believe is a piece of cheese, but it calls itself `AMD FirePro W2100 (FireGL V)`
I did used to get problems with this graphics card 4 years ago (Think it was drivers), but for the last 3½ it's been solid as a rock.

**Comment by robmikh** [comment]
Sorry for the delay, would you be willing to try another program to see if you can reproduce the issue there?
The CaptureVideoSample project is similar to this one, but this release uses the video processor to scale content instead of the encoder:
https://github.com/robmikh/CaptureVideoSample/releases/tag/v0.1.3-mf-prerelease
