### ISSUE TITLE
Option to disable upscaling (?)

### ISSUE THREAD

**Issue by MarcAnt01** [robmikh/SimpleRecorder#41]
When I select a certain resolution and record a small window it ends up having the same resolution of the full screen, I suppose a kind of upscaling is performed. Is there a way to disable it and keep the original window resolution? On high res displays (such as 5k) this seems to affect the recording smoothness.

**Comment by robmikh** [comment]
You'll need to compose the texture that gets sent to the encoder differently. I would look at `CaptureFrameWait.cs` where `CopySubresourceRegion` is called. You'll want to copy this into a larger texture, and then feed that larger texture to the encoder instead of allowing it to upscale by itself. Don't forget to set those input size settings on the encoder so that it doesn't expect a smaller texture.
