### ISSUE TITLE
Black stripes on the right and bottom

### ISSUE THREAD

**Issue by schabau** [robmikh/SimpleRecorder#46]
Hello,

I have black stripes on the right and bottom. Can this be prevented in any way?

Many greetings
schabau

**Comment by robmikh** [comment]
This shouldn't be present on Windows 11. On Windows 10, the application needs to be modified to query the initial window size from the DWM (DWMWA_EXTENDED_FRAME_BOUNDS). That would require creating the capture item from a HWND instead of using the picker, which isn't available to UWP on Windows 10.

Unfortunately, I don't have a public Win32 project on hand that demonstrates this.
